# fly.toml file generated for api-perfectfit on 2022-08-19T23:24:19+05:30

app = "api-perfectfit"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  FRONT_END_URL = "https://perfectfit.ml"
  ADMIN_URL = "http://localhost:3001"
  MONGODB_URI = "mongodb+srv://anirudh:tantry@ecommerce.s6wuv.mongodb.net/PerfectFit?retryWrites=true&w=majority"
  SALT_ROUNDS = 12
  JWT_SECRET = "JWTFORPERFECTFIT"
  JWT_EXPIRES_IN = "15d"
  COOKIE_EXPIRE = 15
  MAIL_TRAP_ENDPOINT = "https://send.api.mailtrap.io/"
  MAIL_TRAP_TOKEN = "a003a6057f680a645eba1e0952656c6b"
  SENDER_EMAIL = "admin@perfectfit.ml"
  CLOUDINARY_URL = "cloudinary://992384269625277:qg0fRf82yYqthLpbC_aBDcTdpls@anirudh-tantry"
  CLOUD_NAME = "anirudh-tantry"
  CLOUDINARY_API_KEY = 992384269625277
  CLOUDINARY_API_SECRET = "qg0fRf82yYqthLpbC_aBDcTdpls"
  RAZORPAY_API_KEY = "rzp_test_BpH9LhDiyHsH4X"
  RAZORPAY_API_SECRET = "991OmNr7xsaaCevMLeribcMx"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
